# Site settings
title:        Geoffrey Huntley
email:        ghuntley@ghuntley.com
author:       Geoffrey Huntley
description:  "Geoffrey Huntley's Blog"
baseurl:      ""
url:          "https://ghuntley.com"
repo_url:     "https://github.com/ghuntley/ghuntley.github.io"
gravatar_url: "http://www.gravatar.com/avatar/23d4d2451f74764e095f15a739b68a4e"
date_format:  "%b %-d, %Y"



# Google services
google_verification:  "Ygi199GbO9ipejg0519FZUH5JVbWB_qIS9JOke_ulp8"

# Optional features
animated:             false
show_related_posts:   true
show_post_footers:    true
ajaxify_contact_form: false

# Disqus post comments
# (leave blank to disable Disqus)
disqus_shortname: ghuntley

# Facebook Comments plugin
# (leave blank to disable Facebook Comments, otherwise set it to true)
facebook_comments:
facebook_appid:
facebook_comments_number: 10

# Social icons
github_username: ghuntley
bitbucket_username:
stackoverflow_id:
twitter_username: geoffreyhuntley
google_plus_id:
linkedin_username: geoffreyhuntley
angellist_username:
medium_id:
bitcoin_url:
paypal_url:
flattr_button:

# Post sharing icons
show_sharing_icons: true
share_text: "Share this post!"
# Change to 'true' to enable individual icons
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: true
share_digg: false
share_tumblr: false
share_reddit: true
share_stumbleupon: false
share_hackernews: true

# Build settings
markdown:     kramdown
redcarpet:
  extensions: ['smart', 'tables', 'with_toc_data']
permalink:    "/archive/:year/:month/:day/:title/"
paginate:     15
paginate_path: "page/:num"
category_dir: categories
sass:
  compressed: true

gems:
  - jekyll-paginate
  - jekyll-redirect-from
  - jekyll-sitemap
  - jemoji
